### ISSUE TITLE
Auth_email admin gives problem in registration for moodle 3.0

### ISSUE THREAD

**Issue by federicama** [hrimhari/moodle-auth_emailadmin#9]
Dear hrimhari,

thanks very much for contributing with this plugin. It is very useful for my Mooodle as we have experienced some problems with the self-based registration.

We are going to upgrade our Moodle from 2.7 to 3.0
It is running on Apache Amazon server.

When we upgraded the acceptance environment we have seen that the registration page has some issues in not refreshing after the new user has clicked on "Create new account".

The error message in the logs says:
`
Tue Mar 22 13:52:31.121478 2016] [:error] [pid 21366] [client 80.112.244.206:20031] 39, referer: http://acceptance.MYWEBSITE.com/login/signup.php
[Tue Mar 22 13:52:31.121509 2016] [:error] [pid 21366] [client 80.112.244.206:20031] 39:39, referer: http://acceptance.MYWEBSITE.com/login/signup.php
[Tue Mar 22 13:52:32.946640 2016] [:error] [pid 21366] [client 80.112.244.206:20031] Could not send registration notification to: admin2 , referer: http://acceptance.MYWEBSITE.com/login/signup.php
`

We have 4 admins users, plus a default user with the admin2 account.

I hope it is clear, please let me know if you need more information from my side.
As well if you can pick up this issue easily.

Thanks!
Federica

**Comment by hrimhari** [comment]
The plug-in is telling you that it tried to send a notification to 'admin2' and failed. Most likely it has an invalid email address.You have the following options to solve this issue:Configure the plug-in to send notifications to specific users and not include 'admin2'.Configure a valid email address for 'admin2'.Hope that helps,FelipeOn March 23, 2016 at 9:52 AM federicama <notifications@github.com> wrote:Dear hrimhari,thanks very much for contributing with this plugin. It is very useful for my Mooodle as we have experienced some problems with the self-based registration.We are going to upgrade our Moodle from 2.7 to 3.0 It is running on Apache Amazon server.When we upgraded the acceptance environment we have seen that the registration page has some issues in not refreshing after the new user has clicked on "Create new account".The error message in the logs says:  Tue Mar 22 13:52:31.121478 2016] [:error] [pid 21366] [client 80.112.244.206:20031] 39, referer: http://acceptance.utzacademyonline.com/login/signup.php [Tue Mar 22 13:52:31.121509 2016] [:error] [pid 21366] [client 80.112.244.206:20031] 39:39, referer: http://acceptance.utzacademyonline.com/login/signup.php [Tue Mar 22 13:52:32.946640 2016] [:error] [pid 21366] [client 80.112.244.206:20031] Could not send registration notification to: admin2 , referer: http://acceptance.utzacademyonline.com/login/signup.phpWe have 4 admins users, plus a default user with the admin2 account.I hope it is clear, please let me know if you need more information from my side. As well if you can pick up this issue easily.Thanks! Federica—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by federicama** [comment]
Hi Felipe,

Yes, I thought the same at the beginning but either option 1 either option 2 don't work.
1. I changed the configuration but emails are still sent out to all the administrators
2. the email address is valid. even tested with a different one.

Any suggestion? At the moment I don't have an overview of the logs.
Thanks!

**Comment by hrimhari** [comment]
The only thing that comes to mind is that you may not be actually using the plug-in. In 'Manage authentication', your 'self registration' choice should be 'Email-based self-registration with admin confirmation', not 'Email self-registration'.

**Comment by federicama** [comment]
Unluckly this is not the case, the manage authentication is set up on "Email-based self-registration with admin confirmation".

**Comment by hrimhari** [comment]
No other ideas then, sorry. Maybe you can try to have debug logging enabled and have that sent over?

**Comment by federicama** [comment]
After 10 minutes of waiting, the page refreshed correctly, but I have 85 page exported of debugging!

**Comment by hrimhari** [comment]
If you're not too worried about exposing some potentially sensitive info about your setup, I'd take a look at your debug if you'd send it to felipe (a) carassonet dot org or put it, say, on Mega.nz and share the link by email.

**Comment by federicama** [comment]
Hi Felipe, thanks very much for your interest.
I am going to send you the files by email
